contact_links:
  - name: 📃 Documentation Issue
    url: https://github.com/wizelineacademy/itesm-socioformador-ago-dec-2023-team-02/issues/new
    about: This issue tracker is not for documentation issues. Please file documentation issues here.
  - name: 🤔 Questions and Help
    url: https://github.com/william-monroy
    about: Let's work.
