name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: |
          echo DATABASE_URL="${{ secrets.DATABASE_URL }}" >> ./apps/web/.env
          cat .env
      - run: npm i -g pnpm
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm build
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
